### ISSUE TITLE
Include complete examples

### ISSUE THREAD

**Issue by skrat** [fekr/postagga#14]
It would be beneficial for beginner users to have a complete running example programs, preferably in English.

**Comment by turbopape** [comment]
Hey skrat, thank you for your suggestion !

Actually, you can find samples in the [test file](https://github.com/fekr/postagga/blob/master/test/postagga/core_test.cljc)

please let me know if this can guide you !

**Comment by turbopape** [comment]
I'm Gonna close this as I think the test files provide for usage samples.
Please feel free to file another issue if you're still in need of examples !
